version: "2"

run:
  timeout: 5m

linters:
  enable:
    - gocritic
    - gosec
    - errcheck
    - staticcheck
    - exhaustive
    - noctx
    - prealloc
    - bodyclose

formatters:
  enable:
    - gofmt
    - goimports
